# Generated by Django 4.1.7 on 2023-05-04 07:15

from django.db import migrations, models
import django.db.models.deletion
import nanopay.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nanoassets', '0052_alter_activityhistory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_day', models.DateField(verbose_name='Pay Date')),
                ('amount', models.FloatField(verbose_name='Payment Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Prjct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Legal Entity Name')),
                ('type', models.CharField(choices=[('I', 'Internal'), ('E', 'External')], default='E', max_length=1, verbose_name='Legal Entity Type')),
                ('deposit_bank', models.CharField(max_length=50, null=True, verbose_name='开户行')),
                ('deposit_bank_account', models.CharField(max_length=25, null=True, verbose_name='开户行账号')),
                ('tax_number', models.CharField(max_length=25, null=True, verbose_name='纳税人识别号')),
                ('reg_addr', models.CharField(max_length=50, null=True, verbose_name='注册地址')),
                ('reg_phone', models.CharField(max_length=15, null=True, verbose_name='注册电话')),
                ('prjct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.prjct', verbose_name='Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Contract Name')),
                ('startup', models.DateField(verbose_name='Start Up')),
                ('endup', models.DateField(verbose_name='End Up')),
                ('scanned_copy', models.FileField(upload_to=nanopay.models.contract_scanned_copy_path, verbose_name='Scanned Copy')),
                ('assets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.instance', verbose_name='')),
                ('party_a_list', models.ManyToManyField(related_name='partyas', to='nanopay.legalentity', verbose_name='甲方')),
                ('party_b_list', models.ManyToManyField(related_name='partybs', to='nanopay.legalentity', verbose_name='乙方')),
                ('party_c_list', models.ManyToManyField(blank=True, related_name='partycs', to='nanopay.legalentity', verbose_name='丙方')),
                ('payment_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.paymentterm', verbose_name='Payment Term')),
            ],
        ),
    ]
