# Generated by Django 4.1.7 on 2023-05-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='prjct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.prjct', verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reg_addr',
            field=models.CharField(max_length=50, null=True, verbose_name='注册/工作地址'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reg_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='注册/工作电话'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='tax_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='纳税人识别号'),
        ),
    ]
