# Generated by Django 5.0.5 on 2024-05-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='created_on',
            field=models.DateField(null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='requested_on',
            field=models.DateTimeField(null=True, verbose_name='Requested on'),
        ),
    ]
