# Generated by Django 4.1.7 on 2023-05-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0002_alter_legalentity_prjct_alter_legalentity_reg_addr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='endup',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='startup',
        ),
    ]
