# Generated by Django 5.0.5 on 2024-07-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0002_alter_nonpayrollexpense_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prjct',
            name='allocations',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='allocation list'),
        ),
    ]
