# Generated by Django 4.1.7 on 2023-05-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0003_remove_contract_endup_remove_contract_startup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='party_a_list',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='party_b_list',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='party_c_list',
        ),
    ]
