# Generated by Django 5.0.5 on 2024-07-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0003_prjct_allocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prjct',
            name='allocations',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='allocation list'),
        ),
    ]
