# Generated by Django 4.1.7 on 2023-05-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0004_remove_contract_party_a_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='payment_term',
        ),
    ]
