# Generated by Django 5.0.5 on 2024-10-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0004_alter_prjct_allocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='briefing',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Briefing'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('M', 'Maintenance'), ('N', 'New'), ('R', 'Rental'), ('E', 'Expired'), ('T', 'Terminated')], default='M', max_length=255, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='deposit_bank',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='开户行'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='deposit_bank_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='开户行账号'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='主体名称'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='postal_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal Address'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reg_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='注册地址'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reg_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='注册电话'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='tax_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='纳税人识别号'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='type',
            field=models.CharField(choices=[('I', 'Internal'), ('E', 'External')], default='E', max_length=255, verbose_name='主体类型'),
        ),
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='allocation',
            field=models.CharField(max_length=255, verbose_name='Allocation'),
        ),
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='currency',
            field=models.CharField(choices=[('CNY', '￥'), ('USD', '$')], default='CNY', max_length=255, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='functional_department',
            field=models.CharField(max_length=255, verbose_name='Functional Department'),
        ),
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='global_expense_tracking_id',
            field=models.CharField(max_length=255, verbose_name='Global Expense Tracking ID'),
        ),
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='is_direct_cost',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='N', max_length=255, verbose_name='Is Direct Cost'),
        ),
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='non_payroll_expense_reforecasting',
            field=models.CharField(choices=[('Q0', 'Q0'), ('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3')], default='Q0', max_length=255, verbose_name='Quarterly Reforecasting'),
        ),
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='originating_sub_region',
            field=models.CharField(max_length=255, verbose_name='Originating Sub Region'),
        ),
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='budget_category',
            field=models.CharField(choices=[('D', 'Development Budget'), ('O', 'Operation Budget')], default='O', max_length=255, verbose_name='Budget category'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('I', 'Initialized'), ('A', 'Approved')], default='I', max_length=255, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='plan',
            field=models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-anually'), ('A', 'Anually'), ('C', 'Custom')], default='M', max_length=255, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='prjct',
            name='allocations',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='allocation list'),
        ),
        migrations.AlterField(
            model_name='prjct',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Project Name'),
        ),
    ]
