# Generated by Django 4.1.7 on 2023-05-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0005_remove_contract_payment_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='assets',
        ),
    ]
