# Generated by Django 5.0.5 on 2024-10-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0005_alter_contract_briefing_alter_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商代码'),
        ),
    ]
