# Generated by Django 4.1.7 on 2023-05-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0052_alter_activityhistory_options'),
        ('nanopay', '0006_remove_contract_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='assets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.instance', verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='endup',
            field=models.DateField(auto_now=True, verbose_name='End Up'),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_a_list',
            field=models.ManyToManyField(related_name='partyas', to='nanopay.legalentity', verbose_name='甲方'),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_b_list',
            field=models.ManyToManyField(related_name='partybs', to='nanopay.legalentity', verbose_name='乙方'),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_c_list',
            field=models.ManyToManyField(blank=True, related_name='partycs', to='nanopay.legalentity', verbose_name='丙方'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.paymentterm', verbose_name='Payment Term'),
        ),
        migrations.AddField(
            model_name='contract',
            name='startup',
            field=models.DateField(auto_now=True, verbose_name='Start Up'),
        ),
    ]
