# Generated by Django 5.0.5 on 2024-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0006_alter_legalentity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='budget_system',
            field=models.CharField(choices=[('P', 'PMWeb'), ('N', 'Non-PMWeb')], default='P', max_length=255, verbose_name='Budget system'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='budgeted',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=255, verbose_name='Budget category'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='method',
            field=models.CharField(choices=[('CH', 'cheque'), ('CA', 'cash'), ('WT', 'wire transfer')], default='WT', max_length=255, verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='vat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value Added Tax'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('V', 'Verified'), ('I', 'Initialized'), ('A', 'Approved'), ('R', 'Rejected')], default='I', max_length=255, verbose_name='Request status'),
        ),
    ]
