# Generated by Django 5.0.5 on 2024-11-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0007_paymentrequest_budget_system_paymentrequest_budgeted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('Req', 'Requested'), ('I', 'Initialized'), ('A', 'Approved'), ('Rej', 'Rejected')], default='I', max_length=255, verbose_name='Request status'),
        ),
    ]
