# Generated by Django 4.1.7 on 2023-05-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0007_contract_assets_contract_endup_contract_party_a_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='assets',
        ),
    ]
