# Generated by Django 4.1.7 on 2023-05-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0052_alter_activityhistory_options'),
        ('nanopay', '0009_contract_related_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='related_assets',
        ),
        migrations.AddField(
            model_name='contract',
            name='assets',
            field=models.ManyToManyField(to='nanoassets.instance', verbose_name='Related Assets'),
        ),
    ]
