# Generated by Django 5.0.5 on 2024-11-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0009_remove_paymentrequest_vat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invoice_item',
            new_name='InvoiceItem',
        ),
    ]
