# Generated by Django 4.1.7 on 2023-05-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0010_remove_contract_related_assets_contract_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='endup',
            field=models.DateField(verbose_name='End Up'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='startup',
            field=models.DateField(verbose_name='Start Up'),
        ),
    ]
