# Generated by Django 5.0.5 on 2025-01-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0010_rename_invoice_item_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='non_payroll_expense_year',
            field=models.DecimalField(decimal_places=0, default=2025, max_digits=4, verbose_name='Budget Year'),
        ),
    ]
