# Generated by Django 4.1.7 on 2023-05-04 09:14

from django.db import migrations, models
import nanopay.models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0052_alter_activityhistory_options'),
        ('nanopay', '0012_remove_contract_payment_term_paymentterm_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='assets',
            field=models.ManyToManyField(blank=True, null=True, to='nanoassets.instance', verbose_name='Related Assets'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='party_c_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='partycs', to='nanopay.legalentity', verbose_name='丙方'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='scanned_copy',
            field=models.FileField(blank=True, null=True, upload_to=nanopay.models.path_of_scanned_contract_copy, verbose_name='Scanned Copy'),
        ),
    ]
