# Generated by Django 4.1.7 on 2023-05-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0013_alter_contract_assets_alter_contract_party_c_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='party_c_list',
            field=models.ManyToManyField(blank=True, related_name='partycs', to='nanopay.legalentity', verbose_name='丙方'),
        ),
    ]
