# Generated by Django 4.1.7 on 2023-05-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0052_alter_activityhistory_options'),
        ('nanopay', '0014_alter_contract_party_c_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='assets',
            field=models.ManyToManyField(blank=True, to='nanoassets.instance', verbose_name='Related Assets'),
        ),
    ]
