# Generated by Django 4.1.7 on 2023-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0015_alter_contract_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='scanned_copy',
            field=models.FileField(blank=True, null=True, upload_to='scanned_contract_copy/', verbose_name='Scanned Copy'),
        ),
    ]
