# Generated by Django 4.1.7 on 2023-05-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0017_alter_paymentterm_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('M', 'Maintenance'), ('N', 'New')], default='M', max_length=1, verbose_name='Contract Type'),
        ),
    ]
