# Generated by Django 4.1.7 on 2023-05-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0018_contract_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='name',
            new_name='briefing',
        ),
    ]
