# Generated by Django 4.1.7 on 2023-05-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0019_rename_name_contract_briefing'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentterm',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
