# Generated by Django 4.1.7 on 2023-05-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0020_paymentterm_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentterm',
            name='paid_on',
            field=models.DateField(null=True, verbose_name='Paid on'),
        ),
    ]
