# Generated by Django 4.1.7 on 2023-05-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0021_paymentterm_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterm',
            name='paid_on',
            field=models.DateField(blank=True, null=True, verbose_name='Paid on'),
        ),
    ]
