# Generated by Django 4.1.7 on 2023-05-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0022_alter_paymentterm_paid_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentterm',
            name='paid',
        ),
    ]
