# Generated by Django 4.1.7 on 2023-05-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0024_alter_legalentity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('M', 'Maintenance'), ('N', 'New'), ('R', 'Rental'), ('E', 'Expired')], default='M', max_length=1, verbose_name='Contract Type'),
        ),
    ]
