# Generated by Django 4.1.7 on 2023-05-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0025_alter_contract_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['startup']},
        ),
        migrations.AlterModelOptions(
            name='legalentity',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='plan',
            field=models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-anually'), ('A', 'Anually'), ('C', 'Custom')], default='M', max_length=1, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='pay_day',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
