# Generated by Django 4.1.7 on 2023-05-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0029_alter_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='party_a_list',
            field=models.ManyToManyField(related_name='partyas', to='nanopay.legalentity', verbose_name='Party A'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='party_b_list',
            field=models.ManyToManyField(related_name='partybs', to='nanopay.legalentity', verbose_name='Party B'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='scanned_copy',
            field=models.FileField(blank=True, null=True, upload_to='contract_scanned_copy/%Y/', verbose_name='Scanned Copy'),
        ),
    ]
