# Generated by Django 4.1.7 on 2023-05-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0031_alter_contract_scanned_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('M', 'Maintenance'), ('N', 'New'), ('R', 'Rental'), ('E', 'Expired'), ('T', 'Terminated')], default='M', max_length=1, verbose_name='Contract Type'),
        ),
    ]
