# Generated by Django 4.1.7 on 2023-05-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0034_alter_contract_briefing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='briefing',
            field=models.CharField(max_length=50, null=True, verbose_name='Briefing'),
        ),
    ]
