# Generated by Django 4.1.7 on 2023-05-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0053_activityhistory_contract'),
        ('nanopay', '0037_alter_contract_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='assets',
            field=models.ManyToManyField(blank=True, to='nanoassets.instance', verbose_name='Assets associated with'),
        ),
    ]
