# Generated by Django 4.1.7 on 2023-05-17 00:55

from django.db import migrations, models
import nanopay.models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0038_alter_contract_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='scanned_copy',
            field=models.FileField(blank=True, null=True, upload_to=nanopay.models.contract_scanned_copy_path, verbose_name='Scanned Copy'),
        ),
    ]
