# Generated by Django 4.1.7 on 2023-05-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0039_alter_contract_scanned_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='endup',
            field=models.DateField(null=True, verbose_name='To'),
        ),
    ]
