# Generated by Django 4.1.7 on 2023-05-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0040_alter_contract_endup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='startup',
            field=models.DateField(null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('M', 'Maintenance'), ('N', 'New'), ('R', 'Rental'), ('E', 'Expired'), ('T', 'Terminated')], default='M', max_length=1, verbose_name='Contract Type'),
        ),
    ]
