# Generated by Django 4.1.7 on 2023-05-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0041_alter_contract_startup_alter_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='party_b_list',
            field=models.ManyToManyField(related_name='partybs', to='nanopay.legalentity', verbose_name='Party B'),
        ),
    ]
