# Generated by Django 4.1.7 on 2023-05-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0042_alter_contract_party_b_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='party_a_list',
            field=models.ManyToManyField(related_name='partyas', to='nanopay.legalentity', verbose_name='Party A'),
        ),
    ]
