# Generated by Django 4.1.7 on 2023-05-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0043_alter_contract_party_a_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='briefing',
            field=models.CharField(max_length=50, null=True, verbose_name='Briefing'),
        ),
    ]
