# Generated by Django 4.1.7 on 2023-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0044_alter_contract_briefing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='endup',
            field=models.DateField(blank=True, null=True, verbose_name='To'),
        ),
    ]
