# Generated by Django 4.1.7 on 2023-05-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0045_alter_contract_endup'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentterm',
            name='recurring',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Recurring'),
        ),
    ]
