# Generated by Django 4.1.7 on 2023-05-19 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nanopay.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanopay', '0046_paymentterm_recurring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentterm',
            options={'ordering': ['pay_day']},
        ),
        migrations.AlterField(
            model_name='contract',
            name='briefing',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Briefing'),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the particular request', primary_key=True, serialize=False, verbose_name='Request case ID')),
                ('status', models.CharField(choices=[('I', 'Initialized'), ('A', 'Approved')], default='I', max_length=1, verbose_name='Request status')),
                ('requested_on', models.DateField(blank=True, null=True, verbose_name='Requested on')),
                ('approved_on', models.DateField(blank=True, null=True, verbose_name='Approved on')),
                ('invoice', models.FileField(blank=True, null=True, upload_to=nanopay.models.invoice_scanned_copy_path, verbose_name='Scanned Copy of Invoice')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.paymentterm', verbose_name='Payment Term')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
            options={
                'ordering': ['requested_on'],
            },
        ),
        migrations.CreateModel(
            name='NonPayrollExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_payroll_expense_year', models.CharField(max_length=4, verbose_name='Budget Year')),
                ('non_payroll_expense_reforecasting', models.CharField(choices=[('Q0', 'Q0'), ('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3')], default='Q0', max_length=2, verbose_name='Quarterly Reforecasting')),
                ('originating_sub_region', models.CharField(max_length=32, verbose_name='Originating Sub Region')),
                ('functional_department', models.CharField(max_length=32, verbose_name='Functional Department')),
                ('global_gl_account', models.PositiveIntegerField(verbose_name='Global GL Account')),
                ('vendor', models.CharField(max_length=64, verbose_name='Vendor')),
                ('global_expense_tracking_id', models.CharField(max_length=16, verbose_name='Global Expense Tracking ID')),
                ('currency', models.CharField(choices=[('CNY', 'CNY'), ('USD', 'USD')], default='CNY', max_length=3, verbose_name='Currency')),
                ('allocation', models.CharField(max_length=128, verbose_name='Allocation')),
                ('description', models.TextField(verbose_name='Description')),
                ('jan', models.PositiveIntegerField(default=0, verbose_name='Jan')),
                ('feb', models.PositiveIntegerField(default=0, verbose_name='Feb')),
                ('mar', models.PositiveIntegerField(default=0, verbose_name='Mar')),
                ('apr', models.PositiveIntegerField(default=0, verbose_name='Apr')),
                ('may', models.PositiveIntegerField(default=0, verbose_name='May')),
                ('jun', models.PositiveIntegerField(default=0, verbose_name='Jun')),
                ('jul', models.PositiveIntegerField(default=0, verbose_name='Jul')),
                ('aug', models.PositiveIntegerField(default=0, verbose_name='Aug')),
                ('sep', models.PositiveIntegerField(default=0, verbose_name='Sep')),
                ('oct', models.PositiveIntegerField(default=0, verbose_name='Oct')),
                ('nov', models.PositiveIntegerField(default=0, verbose_name='Nov')),
                ('dec', models.PositiveIntegerField(default=0, verbose_name='Dec')),
                ('is_direct_cost', models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], default='N', max_length=1, verbose_name='Is Direct Cost')),
                ('created_on', models.DateField(null=True, verbose_name='Created on')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['non_payroll_expense_year', 'non_payroll_expense_reforecasting', 'allocation'],
            },
        ),
    ]
