# Generated by Django 4.1.7 on 2023-05-19 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0047_alter_paymentterm_options_alter_contract_briefing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='non_payroll_expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.nonpayrollexpense', verbose_name='Non Payroll Expense'),
        ),
    ]
