# Generated by Django 4.1.7 on 2023-05-19 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0048_paymentrequest_non_payroll_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='case_id',
            new_name='request_id',
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='non_payroll_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.nonpayrollexpense', verbose_name='Non Payroll Expense'),
        ),
    ]
