# Generated by Django 4.1.7 on 2023-05-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0049_rename_case_id_paymentrequest_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='vendor',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Vendor'),
        ),
    ]
