# Generated by Django 4.1.7 on 2023-05-19 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0050_alter_nonpayrollexpense_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='invoice',
            new_name='scanned_copy',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='amount',
            field=models.PositiveIntegerField(help_text='VAT included', null=True, verbose_name='Ivoice Amount'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the particular request', primary_key=True, serialize=False, verbose_name='Request ID'),
        ),
    ]
