# Generated by Django 4.1.7 on 2023-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0056_alter_nonpayrollexpense_apr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Invoice Amount'),
        ),
    ]
