# Generated by Django 4.1.7 on 2023-05-19 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nanopay.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanopay', '0057_alter_paymentrequest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Requested by'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='requested_on',
            field=models.DateField(null=True, verbose_name='Requested on'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='scanned_copy',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=nanopay.models.invoice_scanned_copy_path, verbose_name='Scanned Copy of Invoice'),
        ),
    ]
