# Generated by Django 4.1.7 on 2023-05-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0059_contract_non_payroll_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='non_payroll_expense',
        ),
    ]
