# Generated by Django 4.1.7 on 2023-05-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0060_remove_paymentrequest_non_payroll_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='description',
            field=models.TextField(unique=True, verbose_name='Description'),
        ),
    ]
