# Generated by Django 4.1.7 on 2023-05-22 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0061_alter_nonpayrollexpense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='non_payroll_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.nonpayrollexpense', verbose_name='Non Payroll Expense'),
        ),
    ]
