# Generated by Django 4.1.7 on 2023-05-22 03:20

from django.db import migrations, models
import nanopay.models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0062_paymentrequest_non_payroll_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='scanned_copy',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=nanopay.models.contract_scanned_copy_path, verbose_name='Scanned Copy'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='scanned_copy',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=nanopay.models.invoice_scanned_copy_path, verbose_name='Scanned Copy of Invoice'),
        ),
    ]
