# Generated by Django 4.1.7 on 2023-05-22 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0063_alter_contract_scanned_copy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentterm',
            old_name='paid_on',
            new_name='applied_on',
        ),
    ]
