# Generated by Django 4.1.7 on 2023-05-22 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanopay', '0064_rename_paid_on_paymentterm_applied_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='approved_on',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='IT_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='IT reviewed by'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='IT_reviewed_on',
            field=models.DateField(blank=True, null=True, verbose_name='IT reviewed on'),
        ),
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='requested_on',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Requested on'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='applied_on',
            field=models.DateField(blank=True, null=True, verbose_name='Applied on'),
        ),
    ]
