# Generated by Django 4.1.7 on 2023-05-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0065_remove_paymentrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='request_id',
            new_name='id',
        ),
    ]
