# Generated by Django 4.1.7 on 2023-05-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0066_rename_request_id_paymentrequest_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'ordering': ['-status', 'requested_on']},
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='times',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Times of Payment'),
        ),
    ]
