# Generated by Django 4.1.7 on 2023-05-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0067_alter_paymentrequest_options_paymentrequest_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='times',
        ),
    ]
