# Generated by Django 4.1.7 on 2023-05-24 09:32

from django.db import migrations, models
import nanopay.models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0068_remove_paymentrequest_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='paper_form',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=None, verbose_name='Paper Form'),
        ),
    ]
