# Generated by Django 4.1.7 on 2023-05-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0069_paymentrequest_paper_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='paper_form',
        ),
    ]
