# Generated by Django 4.1.7 on 2023-05-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0070_remove_paymentrequest_paper_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='currency',
            field=models.CharField(choices=[('CNY', '￥'), ('USD', '$')], default='CNY', max_length=3, verbose_name='Currency'),
        ),
    ]
