# Generated by Django 4.1.7 on 2023-05-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0071_alter_nonpayrollexpense_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.CharField(max_length=50, verbose_name='主体名称'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reg_addr',
            field=models.CharField(max_length=50, null=True, verbose_name='注册地址'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reg_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='注册电话'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='type',
            field=models.CharField(choices=[('I', 'Internal'), ('E', 'External')], default='E', max_length=1, verbose_name='主体类型'),
        ),
    ]
