# Generated by Django 4.1.7 on 2023-05-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0072_alter_legalentity_name_alter_legalentity_reg_addr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentterm',
            options={'ordering': ['contract', 'pay_day']},
        ),
    ]
