# Generated by Django 4.1.7 on 2023-05-31 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0073_alter_paymentterm_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='non_payroll_expense',
        ),
    ]
