# Generated by Django 4.1.7 on 2023-06-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0074_remove_contract_non_payroll_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='briefing',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Briefing'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='deposit_bank',
            field=models.CharField(max_length=64, null=True, verbose_name='开户行'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='deposit_bank_account',
            field=models.CharField(max_length=32, null=True, verbose_name='开户行账号'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.CharField(max_length=64, verbose_name='主体名称'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reg_addr',
            field=models.CharField(max_length=64, null=True, verbose_name='注册地址'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reg_phone',
            field=models.CharField(max_length=16, null=True, verbose_name='注册电话'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='tax_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='纳税人识别号'),
        ),
        migrations.AlterField(
            model_name='prjct',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Project Name'),
        ),
    ]
