# Generated by Django 4.1.7 on 2023-06-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0075_alter_contract_briefing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='postal_addr',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Postal Address'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='deposit_bank',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='开户行'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='deposit_bank_account',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='开户行账号'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='主体名称'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reg_addr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注册地址'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reg_phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='注册电话'),
        ),
        migrations.AlterField(
            model_name='prjct',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='Project Name'),
        ),
    ]
