# Generated by Django 4.1.7 on 2023-06-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0076_legalentity_postal_addr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='编码'),
        ),
    ]
