# Generated by Django 4.1.7 on 2023-12-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0077_legalentity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
