# Generated by Django 4.1.7 on 2024-02-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0080_alter_paymentterm_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonpayrollexpense',
            name='non_payroll_expense_year',
            field=models.DecimalField(decimal_places=0, default=2024, max_digits=4, verbose_name='Budget Year'),
        ),
    ]
