


def paper_form_path(instance, filename):
    file_name_base, file_name_ext = os.path.splitext(filename)
    file_name = str(instance.id) + '_' + file_name_base + '_generated by_' + instance.requested_by.username + file_name_ext
    file_path = 'uploads/payment_request/' + str(datetime.date.today().year)
    full_file_name = os.path.join(file_path, file_name)

    return full_file_name
