# Generated by Django 4.2.13 on 2024-05-30 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branchSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Site / Branch Office Name')),
                ('country', models.CharField(blank=True, max_length=128, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, max_length=128, null=True, verbose_name='Region')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('addr', models.CharField(max_length=256, null=True, verbose_name='Site Address')),
                ('postal', models.PositiveIntegerField(null=True, verbose_name='Postal code')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(blank=True, null=True, verbose_name='on')),
                ('db_table_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='db_table_name')),
                ('db_table_pk', models.CharField(blank=True, max_length=32, null=True, verbose_name='db_table_pk')),
                ('order', models.CharField(default='1', max_length=50, verbose_name='Order No.')),
                ('configPara', models.CharField(max_length=50, verbose_name='Parameter')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('is_secret', models.BooleanField(default=False, verbose_name='Cipher')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activation')),
            ],
        ),
        migrations.CreateModel(
            name='configClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Class Name')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Class Description')),
            ],
        ),
        migrations.CreateModel(
            name='disposalRequest',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the particular request', primary_key=True, serialize=False, verbose_name='Request case ID')),
                ('status', models.CharField(choices=[('I', 'Initialized'), ('A', 'Approved')], default='I', max_length=1, verbose_name='Request status')),
                ('type', models.CharField(choices=[('S', 'Scraping'), ('R', 'Reusing'), ('B', 'Buying back')], default='S', max_length=1, verbose_name='Request type')),
                ('requested_on', models.DateField(auto_now_add=True, null=True, verbose_name='Requested on')),
                ('approved_on', models.DateField(blank=True, null=True, verbose_name='Approved on')),
            ],
            options={
                'ordering': ['requested_on'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('serial_number', models.CharField(help_text='enter serial #', max_length=128, primary_key=True, serialize=False, verbose_name='Serial #')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('inUSE', 'in Use'), ('inREPAIR', 'in Repair'), ('SCRAPPED', 'Scrapped'), ('buyBACK', 'BuyBack'), ('reUSE', 'Reuse')], default='Available', help_text='Asset availability', max_length=16, verbose_name='Status')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hostname')),
                ('eol_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'ordering': ['sub_category', 'manufacturer', 'name'],
            },
        ),
    ]
