# Generated by Django 4.1.7 on 2023-03-21 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nanoassets.manufacturer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "serial_number",
                    models.CharField(
                        help_text="enter serial #",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("m", "Maintenance"),
                            ("a", "Available"),
                            ("u", "In use"),
                        ],
                        default="a",
                        help_text="Asset availability",
                        max_length=1,
                    ),
                ),
                ("eol_date", models.DateField(blank=True, null=True)),
                (
                    "model_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nanoassets.modeltype",
                        verbose_name="Model / Type",
                    ),
                ),
            ],
        ),
    ]
