# Generated by Django 4.1.7 on 2023-03-23 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nanoassets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instance", options={"ordering": ["model_type"]},
        ),
        migrations.AddField(
            model_name="instance",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
