# Generated by Django 4.2.13 on 2024-05-30 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanoassets', '0001_initial'),
        ('nanobase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltype',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanobase.subcategory', verbose_name='Sub-Catetory'),
        ),
        migrations.AddField(
            model_name='instance',
            name='branchSite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.branchsite', verbose_name='Site / Branch Office'),
        ),
        migrations.AddField(
            model_name='instance',
            name='disposal_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.disposalrequest', verbose_name='Disposal Request'),
        ),
        migrations.AddField(
            model_name='instance',
            name='model_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.modeltype', verbose_name='Model / Type'),
        ),
        migrations.AddField(
            model_name='instance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='disposalrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='disposalrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Requested by'),
        ),
        migrations.AddField(
            model_name='config',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='by'),
        ),
        migrations.AddField(
            model_name='config',
            name='configClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.configclass', verbose_name='Config Class'),
        ),
        migrations.AddField(
            model_name='branchsite',
            name='onSiteTech',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'IT China'}, to=settings.AUTH_USER_MODEL, verbose_name='Onsite IT Support'),
        ),
    ]
