# Generated by Django 5.0.5 on 2024-05-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposalrequest',
            name='requested_on',
            field=models.DateField(blank=True, null=True, verbose_name='Requested on'),
        ),
    ]
