# Generated by Django 4.1.7 on 2023-03-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0002_alter_instance_options_instance_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('Maintenance', '维修'), ('Available', '备用'), ('In use', '在用')], default='Available', help_text='Asset availability', max_length=20),
        ),
    ]
