# Generated by Django 5.0.5 on 2024-10-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0003_alter_disposalrequest_requested_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
    ]
