# Generated by Django 4.1.7 on 2023-03-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0004_alter_instance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('Maintenance', 'in Repair'), ('Available', 'spare'), ('In use', 'in Use')], default='Available', help_text='Asset availability', max_length=15),
        ),
    ]
