# Generated by Django 4.1.7 on 2023-03-28 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanoassets', '0005_alter_instance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('Available', 'Spare'), ('In use', 'in Use'), ('Maintenance', 'in Repair'), ('Disposal', 'Scrapped')], default='Available', help_text='Asset availability', max_length=15),
        ),
        migrations.CreateModel(
            name='ScrapRequest',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid3, help_text='Unique ID for the particular request', primary_key=True, serialize=False, verbose_name='')),
                ('status', models.CharField(choices=[('I', 'Initialized'), ('A', 'Approved')], default='I', max_length=1, verbose_name='Request status')),
                ('requested_on', models.DateField(blank=True, null=True, verbose_name='Requested on')),
                ('approved_on', models.DateField(blank=True, null=True, verbose_name='Approved on')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approve_by+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.instance', verbose_name='Instance')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_by+', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
        ),
    ]
