# Generated by Django 5.0.5 on 2024-10-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0005_alter_config_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsite',
            name='addr',
            field=models.CharField(max_length=255, null=True, verbose_name='Site Address'),
        ),
        migrations.AlterField(
            model_name='branchsite',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='branchsite',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='branchsite',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Site / Branch Office Name'),
        ),
        migrations.AlterField(
            model_name='branchsite',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='config',
            name='configPara',
            field=models.CharField(max_length=255, verbose_name='Parameter'),
        ),
        migrations.AlterField(
            model_name='config',
            name='db_table_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='db_table_name'),
        ),
        migrations.AlterField(
            model_name='config',
            name='db_table_pk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='db_table_pk'),
        ),
        migrations.AlterField(
            model_name='config',
            name='order',
            field=models.CharField(default='1', max_length=255, verbose_name='Order No.'),
        ),
        migrations.AlterField(
            model_name='configclass',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Class Description'),
        ),
        migrations.AlterField(
            model_name='configclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='disposalrequest',
            name='status',
            field=models.CharField(choices=[('I', 'Initialized'), ('A', 'Approved')], default='I', max_length=255, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='disposalrequest',
            name='type',
            field=models.CharField(choices=[('S', 'Scraping'), ('R', 'Reusing'), ('B', 'Buying back')], default='S', max_length=255, verbose_name='Request type'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='serial_number',
            field=models.CharField(help_text='enter serial #', max_length=255, primary_key=True, serialize=False, verbose_name='Serial #'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('inUSE', 'in Use'), ('inREPAIR', 'in Repair'), ('SCRAPPED', 'Scrapped'), ('buyBACK', 'BuyBack'), ('reUSE', 'Reuse')], default='Available', help_text='Asset availability', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modeltype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
