# Generated by Django 4.1.7 on 2023-03-28 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0006_alter_instance_status_scraprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraprequest',
            name='case_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the particular request', primary_key=True, serialize=False, verbose_name=''),
        ),
    ]
