# Generated by Django 4.1.7 on 2023-03-30 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanoassets', '0008_alter_instance_options_alter_scraprequest_case_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='scrap_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_request', to='nanoassets.scraprequest', verbose_name='Scrap Request'),
        ),
        migrations.AlterField(
            model_name='scraprequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='scraprequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Requested by'),
        ),
    ]
