# Generated by Django 4.1.7 on 2023-03-31 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0010_remove_scraprequest_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='scrap_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.scraprequest', verbose_name='Scrap Request'),
        ),
    ]
