# Generated by Django 4.1.7 on 2023-03-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0011_alter_instance_scrap_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('U', 'in Use'), ('R', 'in Repair'), ('S', 'Scrapped')], default='Available', help_text='Asset availability', max_length=15),
        ),
    ]
