# Generated by Django 4.1.7 on 2023-04-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0012_alter_instance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraprequest',
            options={'permissions': [('can_approve_scrapping_request', 'Can approve scrapping request')]},
        ),
    ]
