# Generated by Django 4.1.7 on 2023-04-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0013_alter_scraprequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraprequest',
            options={'permissions': [('can_approve_scrapping_request', 'Can approve scrapping request'), ('can_apply_scrapping_request', 'Can apply for scrapping request')]},
        ),
    ]
