# Generated by Django 4.1.7 on 2023-04-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0014_alter_scraprequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraprequest',
            options={},
        ),
    ]
