# Generated by Django 4.1.7 on 2023-04-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0015_alter_scraprequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraprequest',
            options={'ordering': ['requested_on']},
        ),
    ]
