# Generated by Django 4.1.7 on 2023-04-10 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanoassets', '0021_alter_branchsite_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchsite',
            name='onSiteTechnican',
        ),
        migrations.AddField(
            model_name='branchsite',
            name='onSiteTechnican',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Onsite IT Support'),
        ),
    ]
