# Generated by Django 4.1.7 on 2023-04-10 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanoassets', '0022_remove_branchsite_onsitetechnican_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchsite',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='branchsite',
            name='city',
        ),
        migrations.RemoveField(
            model_name='branchsite',
            name='country',
        ),
        migrations.RemoveField(
            model_name='branchsite',
            name='name',
        ),
        migrations.RemoveField(
            model_name='branchsite',
            name='onSiteTechnican',
        ),
        migrations.RemoveField(
            model_name='branchsite',
            name='region',
        ),
        migrations.AddField(
            model_name='branchsite',
            name='onSiteTech',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Onsite IT Support'),
        ),
        migrations.AddField(
            model_name='branchsite',
            name='siteAddr',
            field=models.CharField(max_length=50, null=True, verbose_name='Site Address'),
        ),
        migrations.AddField(
            model_name='branchsite',
            name='siteCity',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='siteRegion', chained_model_field='siteRegion', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='branchsite',
            name='siteCountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='branchsite',
            name='siteName',
            field=models.CharField(max_length=50, null=True, verbose_name='Site Branch Office Name'),
        ),
        migrations.AddField(
            model_name='branchsite',
            name='siteRegion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='siteCountry', chained_model_field='siteCountry', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region'),
        ),
    ]
