# Generated by Django 4.1.7 on 2023-04-10 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanoassets', '0023_remove_branchsite_addr_remove_branchsite_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsite',
            name='onSiteTech',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Onsite IT Support'),
        ),
    ]
