# Generated by Django 4.1.7 on 2023-04-10 07:31

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('nanoassets', '0024_alter_branchsite_onsitetech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsite',
            name='siteCity',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='siteRegion', chained_model_field='siteRegion', on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='branchsite',
            name='siteRegion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='siteCountry', chained_model_field='siteCountry', on_delete=django.db.models.deletion.CASCADE, to='cities_light.region'),
        ),
    ]
