# Generated by Django 4.1.7 on 2023-04-10 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('nanoassets', '0025_alter_branchsite_sitecity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsite',
            name='siteRegion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='Province /  State'),
        ),
    ]
