# Generated by Django 4.1.7 on 2023-04-10 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('nanoassets', '0027_alter_branchsite_sitecity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchsite',
            name='siteAddr',
        ),
        migrations.RemoveField(
            model_name='branchsite',
            name='siteCity',
        ),
        migrations.RemoveField(
            model_name='branchsite',
            name='siteCountry',
        ),
        migrations.RemoveField(
            model_name='branchsite',
            name='siteName',
        ),
        migrations.RemoveField(
            model_name='branchsite',
            name='siteRegion',
        ),
        migrations.AddField(
            model_name='branchsite',
            name='addr',
            field=models.CharField(max_length=50, null=True, verbose_name='Site Address'),
        ),
        migrations.AddField(
            model_name='branchsite',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchsite',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='branchsite',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Site Branch Office Name'),
        ),
        migrations.AddField(
            model_name='branchsite',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='Province /  State'),
        ),
    ]
