# Generated by Django 4.1.7 on 2023-04-10 07:56

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('nanoassets', '0028_remove_branchsite_siteaddr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchsite',
            name='region',
        ),
        migrations.AlterField(
            model_name='branchsite',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
    ]
