# Generated by Django 4.1.7 on 2023-04-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0029_remove_branchsite_region_alter_branchsite_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchsite',
            name='city',
        ),
    ]
