# Generated by Django 4.1.7 on 2023-04-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0030_remove_branchsite_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='branchSite',
        ),
    ]
