# Generated by Django 4.1.7 on 2023-04-10 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanoassets', '0031_delete_branchsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='branchSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Site Branch Office Name')),
                ('addr', models.CharField(max_length=50, null=True, verbose_name='Site Address')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country', verbose_name='Country')),
                ('onSiteTech', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Onsite IT Support')),
            ],
        ),
    ]
