# Generated by Django 4.1.7 on 2023-04-10 08:33

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('nanoassets', '0036_alter_branchsite_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsite',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
    ]
