# Generated by Django 4.1.7 on 2023-04-11 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanoassets', '0037_alter_branchsite_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsite',
            name='onSiteTech',
            field=models.ManyToManyField(limit_choices_to={'user.groups.all()': 'IT China'}, to=settings.AUTH_USER_MODEL, verbose_name='Onsite IT Support'),
        ),
    ]
