# Generated by Django 4.1.7 on 2023-04-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0041_alter_branchsite_onsitetech'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='branchSite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.branchsite', verbose_name='Site / Branch Office'),
        ),
        migrations.AlterField(
            model_name='branchsite',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Site / Branch Office Name'),
        ),
    ]
