# Generated by Django 4.1.7 on 2023-04-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0042_instance_branchsite_alter_branchsite_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchsite',
            name='postal',
            field=models.PositiveIntegerField(null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='branchsite',
            name='addr',
            field=models.CharField(max_length=255, null=True, verbose_name='Site Address'),
        ),
    ]
