# Generated by Django 4.1.7 on 2023-04-13 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0043_branchsite_postal_alter_branchsite_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuragion',
            fields=[
                ('hostname', models.CharField(default=uuid.uuid4, help_text='Hostname', max_length=25, primary_key=True, serialize=False, verbose_name='Hostname')),
            ],
        ),
    ]
