# Generated by Django 4.1.7 on 2023-04-13 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0044_configuragion'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='configuragion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.configuragion', verbose_name='Configuragion'),
        ),
        migrations.AlterField(
            model_name='configuragion',
            name='hostname',
            field=models.CharField(default=uuid.uuid4, help_text='Hostname', max_length=36, primary_key=True, serialize=False, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='serial_number',
            field=models.CharField(default=uuid.uuid4, help_text='enter serial #', max_length=36, primary_key=True, serialize=False),
        ),
    ]
