# Generated by Django 4.1.7 on 2023-04-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0045_instance_configuragion_alter_configuragion_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('inUSE', 'in Use'), ('inREPAIR', 'in Repair'), ('SCRAPPED', 'Scrapped')], default='Available', help_text='Asset availability', max_length=15),
        ),
    ]
