# Generated by Django 4.1.7 on 2023-04-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0046_alter_instance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
