# Generated by Django 4.1.7 on 2023-04-24 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0048_activityhistory_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityhistory',
            name='Instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.instance', verbose_name='IT Assets'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('inUSE', 'in Use'), ('inREPAIR', 'in Repair'), ('SCRAPPED', 'Scrapped'), ('buyBACK', 'BuyBack')], default='Available', help_text='Asset availability', max_length=15),
        ),
    ]
