# Generated by Django 4.1.7 on 2023-04-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0049_alter_activityhistory_instance_alter_instance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ['branchSite', 'status', 'model_type', 'eol_date']},
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('inUSE', 'in Use'), ('inREPAIR', 'in Repair'), ('SCRAPPED', 'Scrapped'), ('buyBACK', 'BuyBack'), ('reUSE', 'Reuse')], default='Available', help_text='Asset availability', max_length=15),
        ),
    ]
