# Generated by Django 4.1.7 on 2023-05-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0033_contract_created_by'),
        ('nanoassets', '0052_alter_activityhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityhistory',
            name='Contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.contract', verbose_name='Contract'),
        ),
    ]
