# Generated by Django 4.1.7 on 2023-06-02 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0053_activityhistory_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsite',
            name='addr',
            field=models.CharField(max_length=256, null=True, verbose_name='Site Address'),
        ),
        migrations.AlterField(
            model_name='branchsite',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='Site / Branch Office Name'),
        ),
        migrations.AlterField(
            model_name='configuragion',
            name='hostname',
            field=models.CharField(default=uuid.uuid4, help_text='Hostname', max_length=32, primary_key=True, serialize=False, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='serial_number',
            field=models.CharField(default=uuid.uuid4, help_text='enter serial #', max_length=32, primary_key=True, serialize=False, verbose_name='Serial #'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('inUSE', 'in Use'), ('inREPAIR', 'in Repair'), ('SCRAPPED', 'Scrapped'), ('buyBACK', 'BuyBack'), ('reUSE', 'Reuse')], default='Available', help_text='Asset availability', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='modeltype',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
