# Generated by Django 4.1.7 on 2023-06-05 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanobase', '0005_alter_subcategory_options_and_more'),
        ('nanoassets', '0054_alter_branchsite_addr_alter_branchsite_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeltype',
            options={'ordering': ['sub_category', 'manufacturer', 'name']},
        ),
        migrations.AddField(
            model_name='modeltype',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanobase.subcategory', verbose_name='Sub-Catetory'),
        ),
        migrations.AlterField(
            model_name='modeltype',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
