# Generated by Django 4.1.7 on 2023-06-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0055_alter_modeltype_options_modeltype_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hostname'),
        ),
    ]
