# Generated by Django 4.1.7 on 2023-06-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0056_instance_hostname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='configuragion',
        ),
    ]
