# Generated by Django 4.1.7 on 2023-06-12 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0057_remove_instance_configuragion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuragion',
        ),
    ]
