# Generated by Django 4.1.7 on 2023-08-28 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanoassets', '0058_delete_configuragion'),
    ]

    operations = [
        migrations.CreateModel(
            name='disposalRequest',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the particular request', primary_key=True, serialize=False, verbose_name='Request case ID')),
                ('status', models.CharField(choices=[('I', 'Initialized'), ('A', 'Approved')], default='I', max_length=1, verbose_name='Request status')),
                ('type', models.CharField(choices=[('S', 'Scraping'), ('R', 'Reusing'), ('B', 'Buying back')], default='S', max_length=1, verbose_name='Request type')),
                ('requested_on', models.DateField(auto_now_add=True, null=True, verbose_name='Requested on')),
                ('approved_on', models.DateField(blank=True, null=True, verbose_name='Approved on')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
            ],
            options={
                'ordering': ['requested_on'],
            },
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ['model_type__sub_category', 'branchSite', 'status', 'model_type', 'eol_date']},
        ),
        migrations.AlterField(
            model_name='modeltype',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.DeleteModel(
            name='ActivityHistory',
        ),
        migrations.AddField(
            model_name='disposalrequest',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.instance', verbose_name='Instance'),
        ),
        migrations.AddField(
            model_name='disposalrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Requested by'),
        ),
    ]
