# Generated by Django 4.1.7 on 2023-08-28 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0059_disposalrequest_alter_instance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposalrequest',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='scrap_request',
        ),
        migrations.AddField(
            model_name='instance',
            name='disposal_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.disposalrequest', verbose_name='Disposal Request'),
        ),
    ]
