# Generated by Django 4.1.7 on 2024-02-06 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanoassets', '0061_delete_scraprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='configClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Class Name')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Class Description')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(blank=True, null=True, verbose_name='on')),
                ('db_table_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='')),
                ('db_table_pk', models.CharField(blank=True, max_length=32, null=True, verbose_name='')),
                ('order', models.CharField(default='1', max_length=50, verbose_name='Order No.')),
                ('value', models.CharField(max_length=50, verbose_name='Parameter')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='by')),
                ('configClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanoassets.configclass', verbose_name='Config Class')),
            ],
        ),
    ]
