# Generated by Django 4.1.7 on 2024-02-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoassets', '0062_configclass_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='value',
            new_name='configPara',
        ),
    ]
