# Generated by Django 4.2.13 on 2024-05-30 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nanobase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanopay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Sub-Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Title')),
                ('work_phone', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='Work Phone')),
                ('postal_addr', models.CharField(blank=True, max_length=128, null=True, verbose_name='Postal Address')),
                ('cellphone', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='Cellphone')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanobase.userdept', verbose_name='Department')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.legalentity', verbose_name='Legal Entiry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(blank=True, null=True, verbose_name='on')),
                ('db_table_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='db_table_name')),
                ('db_table_pk', models.CharField(blank=True, max_length=32, null=True, verbose_name='db_table_pk')),
                ('digital_copy', models.FileField(blank=True, max_length=256, null=True, upload_to=nanobase.models.digital_copy_upload_to, verbose_name='Digital Copy')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='by')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(blank=True, null=True, verbose_name='on')),
                ('db_table_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='db_table_name')),
                ('db_table_pk', models.CharField(blank=True, max_length=32, null=True, verbose_name='db_table_pk')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='by')),
            ],
        ),
    ]
