# Generated by Django 4.1.7 on 2023-06-05 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0076_legalentity_postal_addr_and_more'),
        ('nanobase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Sub-Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Department')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.legalentity', verbose_name=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_addr',
            field=models.CharField(blank=True, default='placeholder', max_length=128, null=True, verbose_name='Postal Address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Cellphone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanobase.userdept', verbose_name=''),
        ),
    ]
