# Generated by Django 5.1.3 on 2025-01-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanobase', '0002_alter_changehistory_db_table_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Work Phone'),
        ),
    ]
