# Generated by Django 4.1.7 on 2023-06-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanobase', '0002_subcategory_userdept_userprofile_legal_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='postal_addr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Postal Address'),
        ),
    ]
