# Generated by Django 4.1.7 on 2023-06-05 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanopay', '0076_legalentity_postal_addr_and_more'),
        ('nanobase', '0003_alter_userprofile_postal_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanobase.userdept', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanopay.legalentity', verbose_name='Legal Entiry'),
        ),
    ]
