# Generated by Django 4.1.7 on 2023-06-14 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanobase', '0005_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(auto_now_add=True, verbose_name='on')),
                ('db_table_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='')),
                ('db_table_pk', models.CharField(blank=True, max_length=32, null=True, verbose_name='')),
                ('change_detail', models.TextField(blank=True, null=True, verbose_name='Change Details')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='by')),
            ],
        ),
    ]
