# Generated by Django 4.1.7 on 2023-06-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanobase', '0006_changehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changehistory',
            name='change_detail',
        ),
        migrations.AddField(
            model_name='changehistory',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
    ]
