# Generated by Django 4.1.7 on 2023-06-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanobase', '0007_remove_changehistory_change_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changehistory',
            name='on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='on'),
        ),
    ]
