# Generated by Django 4.1.7 on 2023-06-16 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nanobase.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanobase', '0008_alter_changehistory_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.DateTimeField(blank=True, null=True, verbose_name='on')),
                ('db_table_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='')),
                ('db_table_pk', models.CharField(blank=True, max_length=32, null=True, verbose_name='')),
                ('digital_copy', models.FileField(blank=True, max_length=256, null=True, upload_to=nanobase.models.digital_copy_upload_to, verbose_name='Digital Copy')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='by')),
            ],
        ),
    ]
