# Generated by Django 4.1.7 on 2024-03-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanobase', '0009_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cellphone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='Cellphone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True, verbose_name='Work Phone'),
        ),
    ]
